### ISSUE TITLE
Different file extension for style sheet

### ISSUE THREAD

**Issue by jasedwards** [sebastianbaar/vscode-add-angular2-files#2]
Would it be possible to add the ability to create a different file besides css?  Maybe something in settings for style sheet extension of something like that?  Since I am using sass this would keep me from having to rename the file every time.

**Comment by sebastianbaar** [comment]
Hey @jasedwards,
thanks for your request. You are now able to specify a stylesheet language "css" (default), "sass", or "less" in your user settings.
1.  Go to user settings (File > Preferences > user settings)
2. Add the following key-value pair:
   `"addNg2.stylesheet": "VALUE"`, where `VALUE` is an ENUM of "css" (default), "sass", or "less"

Hope you like it. Thanks for your feedback!
