### ISSUE TITLE
Indentation is set in tabs instead of spaces

### ISSUE THREAD

**Issue by robertohuertasm** [sebastianbaar/vscode-add-angular2-files#3]
I know this is a controvert subject. I'm using spaces instead of tabs for indentation and using your extension forces me to refactor the generated code every time I use it.

I've been looking into `Angular-cli` and I've seen that they're are also using spaces. I don't know if this is something that you have already decided but maybe it could be nice to create a setting in the extension to make it optional and let the user decide if they want to go with tabs or spaces and in case of the latest, how many spaces they want to use.

Tabs could be dynamically generated in the templates you already have.

**Comment by sebastianbaar** [comment]
hey @robertohuertasm, currently that's not on my milestone, but I would welcome your PR
