### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by alexrainman** [sebastianbaar/vscode-add-angular2-files#4]
Hi,

I am working in this extension https://github.com/alexrainman/vscode-add-nativescript-files based on yours but for vanilla {N} projects.

The problem i have is that the popup to enter the filename works in debug mode but not when i publish the extension.

What am i missing?

Thanks

**Comment by sebastianbaar** [comment]
Hey @alexrainman I tried your extension and it is working fine for me. I get "What's the name of the new component" and I can enter a name and the files are created...

**Comment by alexrainman** [comment]
Yeah i solved the issue and i was able to publish it. Thanks a lot.

**Comment by sebastianbaar** [comment]
Nice to hear! Keep going.. Cheers
