### ISSUE TITLE
Incorrect user setting in documentation

### ISSUE THREAD

**Issue by Cjiq** [sebastianbaar/vscode-add-angular2-files#5]
Hi,

Thanks for creating this plugin, although I found a problem in your documentation.

In your README documentation you refer to the user setting:
`"addNg2.stylesheet": "VALUE"`, where `VALUE` is an ENUM of "css" (default), "sass", or "less"
for changeing the default stylesheet configuration.

It should be changed to:
`"addAngular.stylesheet": "VALUE"`, where `VALUE` is an ENUM of "css" (default), "sass", or "less"
to work with you latest update.

/Cheers Erik

**Comment by sebastianbaar** [comment]
@Cjiq Thanks for pointing this out
