### ISSUE TITLE
Add customized file

### ISSUE THREAD

**Issue by nicoesiea** [sebastianbaar/vscode-add-angular2-files#6]
Hello, sorry for this question but I''m looking for adding or change the content of the added file
Can anybody help me to understand how I should do?
Regards
Nicolas

**Comment by sebastianbaar** [comment]
Hey @nicoesiea,
It’s not possible to change the file content. What kind of changes do you want to do to the content?

Cheers

**Comment by ferhado** [comment]
How to add a index.ts file which contains `export * from module`?
